#!/bin/bash

# Creando la imagen y correr el contenedor
# RUTA_A_DOCKER-COMPOSE.YML

docker-compose build
docker-compose up -d

# Iniciar el servidor
docker exec -i frontend_react_interface_1 npm start